// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/Users/刘超群/Desktop/node.js/article-blog/my-app/src/models/global';
import model_2 from 'C:/Users/刘超群/Desktop/node.js/article-blog/my-app/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
