// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/login","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"登录页","path":"/login","layout":false,"id":"2"},"3":{"name":"文章分类","path":"/home","parentId":"ant-design-pro-layout","id":"3"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'C:/Users/刘超群/Desktop/node.js/my-app/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
